# Site settings
title: lessrandom
email: alistar.huang@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  simple
baseurl: "" # the subpath of your site, e.g. /blog/
url: http://lessrandom.github.io #the base hostname & protocol for your site
# rss_url: /pages/feed.xml
encoding: UTF-8
# Sidebar filter
# Choose 'tag' or 'category' as filter in sidebar.
filter: 'category'

# Social account
twitter: shex1627
weibo:  5761268065
github: shex1627
# codepen:  username
# dribbble: username

# avatar头像及Favicon
avatar: http://i.imgur.com/9pIkVZo.png
favicon: http://i.imgur.com/z7ZGWvZ.jpg

# disqus 设置
disqus:
  shortname:shicheng_huang

# google analytics 设置
ga:
  id:
  url:

# Build settings
permalink: /:year/:month/:day/:title.html
markdown: kramdown
highlighter: rouge
sass:
  style: compressed
